ARG DOCKER_REGISTRY=docker.develop
ARG NODE_VERSION=22.12
ARG NGINX_VERSION=1.25

FROM ${DOCKER_REGISTRY}/base/node:${NODE_VERSION}-alpine as builder
WORKDIR /app
COPY . .
RUN npm install && npm run build:staging

FROM ${DOCKER_REGISTRY}/base/nginx:${NGINX_VERSION}-alpine

ENV REACT_APP_IAM_MODE_DISABLED=true

HEALTHCHECK --interval=60s --timeout=3s --start-period=10s \
    --retries=3 CMD curl -f http://localhost:${SERVER_PORT}/health ||\
    wget --no-verbose --tries=1 --spider http://localhost:${SERVER_PORT}/health || exit 1

COPY --from=builder /app/dist /app/static
COPY nginx.conf /etc/nginx/nginx.conf
RUN find / -perm /6000 -type f -exec chmod a-s {} \; || true